-- OfferOps schema baseline (greenfield bootstrap)
--
-- Generated from the current Drizzle schema (drizzle-kit push on empty DB).
-- This is the starting point for clean staging/production databases.
--
-- Policy:
--   - Applied automatically on a clean database by `pnpm run db:migrate`.
--   - Legacy incremental migrations 0001–0021 are NOT replayed on fresh DBs.
--   - Do not edit this file after it has been applied; add forward migrations instead.
--
-- Idempotency: intended for empty databases only. The migration runner records a
-- checksum after apply; re-runs skip already-applied files. Push-based databases
-- must use `pnpm run db:baseline-align` instead of replaying this SQL.

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: batch_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.batch_status AS ENUM (
    'NEW_BATCH',
    'WAITING_FOR_TRACKER_CAMPAIGNS',
    'OFFER_READY_FOR_LIVE_TESTING',
    'LIVE_TESTS',
    'TESTED',
    'COMPLETED'
);


--
-- Name: batch_traffic_source_platform_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.batch_traffic_source_platform_status AS ENUM (
    'pending',
    'active',
    'completed',
    'failed',
    'skipped'
);


--
-- Name: batch_traffic_source_run_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.batch_traffic_source_run_status AS ENUM (
    'pending',
    'active',
    'completed',
    'failed',
    'skipped'
);


--
-- Name: campaign_manual_close_reason; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.campaign_manual_close_reason AS ENUM (
    'opened_by_mistake',
    'no_traffic_dead_campaign',
    'technical_issue',
    'winners_found'
);


--
-- Name: campaign_platform; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.campaign_platform AS ENUM (
    'ios',
    'android'
);


--
-- Name: campaign_purpose; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.campaign_purpose AS ENUM (
    'testing',
    'working',
    'scaling'
);


--
-- Name: campaign_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.campaign_status AS ENUM (
    'draft',
    'ready',
    'voluum_created',
    'live',
    'ready_for_winner_review',
    'tested',
    'closed'
);


--
-- Name: campaign_winner_source; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.campaign_winner_source AS ENUM (
    'manual_close',
    'target_reached_review'
);


--
-- Name: employee_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.employee_status AS ENUM (
    'active',
    'inactive'
);


--
-- Name: imported_offer_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.imported_offer_status AS ENUM (
    'pending',
    'imported',
    'skipped',
    'error'
);


--
-- Name: notification_severity; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.notification_severity AS ENUM (
    'info',
    'warning',
    'high',
    'critical'
);


--
-- Name: notification_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.notification_type AS ENUM (
    'NEW_BATCH_CREATED',
    'TRACKER_CAMPAIGN_MISSING',
    'INVALID_TAG',
    'DUPLICATE_TRACKER_CAMPAIGN',
    'SUSPICIOUS_BATCH_UPDATE',
    'API_SYNC_FAILURE',
    'TASK_OVERDUE'
);


--
-- Name: offer_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.offer_status AS ENUM (
    'imported',
    'tested',
    'winner',
    'loser'
);


--
-- Name: period_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.period_type AS ENUM (
    'weekly',
    'monthly'
);


--
-- Name: role; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.role AS ENUM (
    'admin',
    'employee'
);


--
-- Name: task_priority; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.task_priority AS ENUM (
    'low',
    'medium',
    'high'
);


--
-- Name: task_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.task_status AS ENUM (
    'TODO',
    'IN_PROGRESS',
    'BLOCKED',
    'DONE'
);


--
-- Name: task_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.task_type AS ENUM (
    'CREATE_IOS_TRACKER_CAMPAIGN',
    'CREATE_ANDROID_TRACKER_CAMPAIGN',
    'GO_LIVE_TRAFFIC_SOURCE_CAMPAIGN',
    'MOVE_WINNERS_TO_SCALED_CAMPAIGN',
    'FIND_WINNERS',
    'PAUSE_TRAFFIC_SOURCE_CAMPAIGNS',
    'CREATE_IOS_CAMPAIGN',
    'CREATE_ANDROID_CAMPAIGN',
    'GO_LIVE',
    'OPTIMIZATION_FOLLOWUP',
    'create_voluum_campaign_ios',
    'create_voluum_campaign_android',
    'take_campaign_live',
    'find_winners',
    'all_traffic_sources_tested',
    'review_winners_target',
    'MANUAL'
);


--
-- Name: tracker_campaign_device; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.tracker_campaign_device AS ENUM (
    'ios',
    'android'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: affiliate_networks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.affiliate_networks (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    name text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: affiliate_networks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.affiliate_networks_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: affiliate_networks_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.affiliate_networks_id_seq OWNED BY public.affiliate_networks.id;


--
-- Name: batch_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.batch_results (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    batch_id integer NOT NULL,
    clicks integer DEFAULT 0 NOT NULL,
    cost numeric DEFAULT '0'::numeric NOT NULL,
    revenue numeric DEFAULT '0'::numeric NOT NULL,
    conversions integer DEFAULT 0 NOT NULL,
    roi numeric,
    winners_count integer DEFAULT 0 NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: batch_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.batch_results_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: batch_results_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.batch_results_id_seq OWNED BY public.batch_results.id;


--
-- Name: batch_traffic_source_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.batch_traffic_source_runs (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    batch_id integer NOT NULL,
    traffic_source_id integer NOT NULL,
    "position" integer NOT NULL,
    status public.batch_traffic_source_run_status DEFAULT 'pending'::public.batch_traffic_source_run_status NOT NULL,
    ios_status public.batch_traffic_source_platform_status DEFAULT 'pending'::public.batch_traffic_source_platform_status NOT NULL,
    android_status public.batch_traffic_source_platform_status DEFAULT 'pending'::public.batch_traffic_source_platform_status NOT NULL,
    ios_campaign_id integer,
    android_campaign_id integer,
    ios_failure_reason text,
    android_failure_reason text,
    ios_completed_at timestamp with time zone,
    android_completed_at timestamp with time zone,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    target_avg_visits_per_offer integer,
    offer_count integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: batch_traffic_source_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.batch_traffic_source_runs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: batch_traffic_source_runs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.batch_traffic_source_runs_id_seq OWNED BY public.batch_traffic_source_runs.id;


--
-- Name: campaign_daily_metrics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campaign_daily_metrics (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    campaign_id integer NOT NULL,
    date date NOT NULL,
    employee_id integer NOT NULL,
    cost numeric DEFAULT '0'::numeric NOT NULL,
    revenue numeric DEFAULT '0'::numeric NOT NULL,
    conversions integer DEFAULT 0 NOT NULL,
    visits integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: campaign_daily_metrics_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.campaign_daily_metrics_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: campaign_daily_metrics_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.campaign_daily_metrics_id_seq OWNED BY public.campaign_daily_metrics.id;


--
-- Name: campaign_winners; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campaign_winners (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    batch_id integer,
    campaign_id integer NOT NULL,
    traffic_source_id integer,
    platform public.campaign_platform NOT NULL,
    offer_id text NOT NULL,
    source public.campaign_winner_source NOT NULL,
    detected_by_employee_id integer,
    detected_at timestamp with time zone DEFAULT now() NOT NULL,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: campaign_winners_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.campaign_winners_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: campaign_winners_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.campaign_winners_id_seq OWNED BY public.campaign_winners.id;


--
-- Name: campaigns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.campaigns (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    batch_id integer,
    platform public.campaign_platform NOT NULL,
    campaign_name text NOT NULL,
    traffic_source_id integer,
    campaign_url text,
    status public.campaign_status DEFAULT 'voluum_created'::public.campaign_status NOT NULL,
    campaign_purpose public.campaign_purpose DEFAULT 'testing'::public.campaign_purpose NOT NULL,
    parent_campaign_id integer,
    affiliate_network_id integer,
    geo text,
    geo_id integer,
    voluum_campaign_id text,
    voluum_campaign_name text,
    traffic_source_campaign_id text,
    traffic_source_campaign_url text,
    live_started_at timestamp with time zone,
    winners_count integer,
    revenue numeric,
    cost numeric,
    clicks integer,
    conversions integer,
    roi numeric,
    notes text,
    close_source text,
    manual_close_reason public.campaign_manual_close_reason,
    manual_close_note text,
    manual_closed_at timestamp with time zone,
    manual_closed_by_employee_id integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: campaigns_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.campaigns_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: campaigns_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.campaigns_id_seq OWNED BY public.campaigns.id;


--
-- Name: daily_reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_reports (
    id integer NOT NULL,
    employee_id integer NOT NULL,
    report_date text NOT NULL,
    offers_uploaded integer DEFAULT 0 NOT NULL,
    batches_created integer DEFAULT 0 NOT NULL,
    batches_tested integer DEFAULT 0 NOT NULL,
    campaigns_moved_to_main integer DEFAULT 0 NOT NULL,
    campaigns_closed integer DEFAULT 0 NOT NULL,
    notes text,
    workspace_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: daily_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.daily_reports_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: daily_reports_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.daily_reports_id_seq OWNED BY public.daily_reports.id;


--
-- Name: employee_workspace_assignments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee_workspace_assignments (
    id integer NOT NULL,
    employee_id integer NOT NULL,
    workspace_id integer NOT NULL,
    role text DEFAULT 'employee'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: employee_workspace_assignments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.employee_workspace_assignments_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: employee_workspace_assignments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.employee_workspace_assignments_id_seq OWNED BY public.employee_workspace_assignments.id;


--
-- Name: employees; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employees (
    id integer NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    password_hash text NOT NULL,
    role public.role DEFAULT 'employee'::public.role NOT NULL,
    status public.employee_status DEFAULT 'active'::public.employee_status NOT NULL,
    active_workspace_id integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: employees_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.employees_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: employees_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.employees_id_seq OWNED BY public.employees.id;


--
-- Name: events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.events (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    type text NOT NULL,
    payload jsonb NOT NULL,
    dedupe_key text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    processed_at timestamp with time zone,
    processing_error text
);


--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.events_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.events_id_seq OWNED BY public.events.id;


--
-- Name: geos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.geos (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: geos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.geos_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: geos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.geos_id_seq OWNED BY public.geos.id;


--
-- Name: goals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goals (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    employee_id integer NOT NULL,
    period_type public.period_type NOT NULL,
    period_start text NOT NULL,
    period_end text NOT NULL,
    target_offers_uploaded integer,
    target_batches_created integer,
    target_batches_tested integer,
    target_campaigns_moved_to_main integer,
    target_geos_tested integer,
    target_traffic_sources_tested integer,
    target_profit_optional numeric,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: goals_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.goals_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: goals_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.goals_id_seq OWNED BY public.goals.id;


--
-- Name: imported_offers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.imported_offers (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    batch_id integer,
    voluum_campaign_id text,
    voluum_offer_id text,
    offer_name text NOT NULL,
    affiliate_network text,
    geo text,
    tag text,
    status public.imported_offer_status DEFAULT 'pending'::public.imported_offer_status NOT NULL,
    error_message text,
    imported_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: imported_offers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.imported_offers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: imported_offers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.imported_offers_id_seq OWNED BY public.imported_offers.id;


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id integer NOT NULL,
    employee_id integer NOT NULL,
    batch_id integer,
    type public.notification_type NOT NULL,
    severity public.notification_severity DEFAULT 'info'::public.notification_severity NOT NULL,
    message text NOT NULL,
    read boolean DEFAULT false NOT NULL,
    workspace_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.notifications_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: notifications_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.notifications_id_seq OWNED BY public.notifications.id;


--
-- Name: offers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.offers (
    id integer NOT NULL,
    batch_id integer NOT NULL,
    offer_id text,
    offer_name text NOT NULL,
    affiliate_network text,
    geo text,
    vertical text,
    status public.offer_status DEFAULT 'imported'::public.offer_status NOT NULL,
    notes text,
    workspace_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: offers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.offers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: offers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.offers_id_seq OWNED BY public.offers.id;


--
-- Name: operational_activity_feed; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.operational_activity_feed (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    event_type text NOT NULL,
    entity_type text NOT NULL,
    entity_id text NOT NULL,
    actor_employee_id integer,
    title text NOT NULL,
    description text,
    metadata_json jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: operational_activity_feed_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.operational_activity_feed_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: operational_activity_feed_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.operational_activity_feed_id_seq OWNED BY public.operational_activity_feed.id;


--
-- Name: operational_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.operational_events (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    entity_type text NOT NULL,
    entity_id text NOT NULL,
    event_type text NOT NULL,
    actor_type text DEFAULT 'system'::text NOT NULL,
    actor_id text,
    source text NOT NULL,
    payload_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: operational_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.operational_events_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: operational_events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.operational_events_id_seq OWNED BY public.operational_events.id;


--
-- Name: performance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.performance (
    id integer NOT NULL,
    batch_id integer NOT NULL,
    date text NOT NULL,
    spend numeric,
    clicks integer,
    conversions integer,
    revenue numeric,
    profit numeric,
    roi numeric,
    cpa numeric,
    epc numeric,
    cvr numeric
);


--
-- Name: performance_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.performance_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: performance_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.performance_id_seq OWNED BY public.performance.id;


--
-- Name: settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settings (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    key text NOT NULL,
    value text
);


--
-- Name: settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.settings_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: settings_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.settings_id_seq OWNED BY public.settings.id;


--
-- Name: testing_batches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.testing_batches (
    id integer NOT NULL,
    employee_id integer NOT NULL,
    batch_name text NOT NULL,
    affiliate_network text NOT NULL,
    geo text NOT NULL,
    traffic_source text NOT NULL,
    vertical text,
    number_of_offers integer,
    tracker_campaign_id text,
    status public.batch_status DEFAULT 'NEW_BATCH'::public.batch_status NOT NULL,
    test_start_date text,
    test_end_date text,
    test_budget numeric,
    notes text,
    clicks_threshold integer,
    spend_threshold numeric,
    days_threshold integer,
    conditions_met_at timestamp with time zone,
    live_at timestamp with time zone,
    traffic_source_voluum_id text,
    affiliate_network_voluum_id text,
    workspace_id integer NOT NULL,
    batch_tag text,
    current_traffic_source_id integer,
    current_workspace_traffic_source_id integer,
    traffic_source_step integer DEFAULT 0 NOT NULL,
    traffic_source_order_snapshot jsonb,
    average_visits_threshold_per_offer integer DEFAULT 25000 NOT NULL,
    optimization_criteria jsonb DEFAULT '{}'::jsonb NOT NULL,
    optimization_run_status text DEFAULT 'not_ready'::text NOT NULL,
    optimization_winners_count integer DEFAULT 0 NOT NULL,
    scaling_candidates_count integer DEFAULT 0 NOT NULL,
    last_optimization_run_at timestamp with time zone,
    scaling_export_status text DEFAULT 'not_exported'::text NOT NULL,
    affiliate_network_id integer,
    geo_id integer,
    test_round integer,
    start_date date,
    test_duration_hours integer DEFAULT 48 NOT NULL,
    voluum_campaign_id text,
    voluum_campaign_name text,
    last_sync_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: testing_batches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.testing_batches_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: testing_batches_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.testing_batches_id_seq OWNED BY public.testing_batches.id;


--
-- Name: todo_tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.todo_tasks (
    id integer NOT NULL,
    employee_id integer NOT NULL,
    related_batch_id integer,
    related_campaign_id integer,
    title text NOT NULL,
    description text,
    task_type public.task_type NOT NULL,
    priority public.task_priority DEFAULT 'medium'::public.task_priority NOT NULL,
    status public.task_status DEFAULT 'TODO'::public.task_status NOT NULL,
    due_date text,
    workspace_id integer NOT NULL,
    flashing boolean DEFAULT false NOT NULL,
    escalated_at timestamp with time zone,
    completed_at timestamp with time zone,
    completed_by_employee_id integer,
    completion_payload jsonb,
    blocked_reason text,
    tracker_campaign_device public.tracker_campaign_device,
    traffic_source_id integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: todo_tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.todo_tasks_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: todo_tasks_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.todo_tasks_id_seq OWNED BY public.todo_tasks.id;


--
-- Name: tracker_campaigns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tracker_campaigns (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    batch_id integer NOT NULL,
    traffic_source_id integer NOT NULL,
    device public.tracker_campaign_device NOT NULL,
    voluum_campaign_id text NOT NULL,
    tag text NOT NULL,
    imported_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: tracker_campaigns_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tracker_campaigns_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tracker_campaigns_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tracker_campaigns_id_seq OWNED BY public.tracker_campaigns.id;


--
-- Name: voluum_affiliate_networks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.voluum_affiliate_networks (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    voluum_id text NOT NULL,
    name text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    deleted_at timestamp with time zone,
    synced_at timestamp with time zone DEFAULT now()
);


--
-- Name: voluum_affiliate_networks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.voluum_affiliate_networks_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: voluum_affiliate_networks_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.voluum_affiliate_networks_id_seq OWNED BY public.voluum_affiliate_networks.id;


--
-- Name: voluum_campaign_mappings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.voluum_campaign_mappings (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    campaign_id text NOT NULL,
    campaign_name text NOT NULL,
    batch_id integer NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: voluum_campaign_mappings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.voluum_campaign_mappings_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: voluum_campaign_mappings_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.voluum_campaign_mappings_id_seq OWNED BY public.voluum_campaign_mappings.id;


--
-- Name: voluum_campaigns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.voluum_campaigns (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    campaign_id text NOT NULL,
    campaign_name text NOT NULL,
    traffic_source_name text,
    traffic_source_id text,
    affiliate_network_name text,
    affiliate_network_id text,
    country text,
    status text,
    primary_tag text,
    all_tags text,
    is_active boolean DEFAULT true NOT NULL,
    deleted_at timestamp with time zone,
    synced_at timestamp with time zone DEFAULT now()
);


--
-- Name: voluum_campaigns_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.voluum_campaigns_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: voluum_campaigns_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.voluum_campaigns_id_seq OWNED BY public.voluum_campaigns.id;


--
-- Name: voluum_offers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.voluum_offers (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    offer_id text NOT NULL,
    offer_name text NOT NULL,
    affiliate_network_name text,
    affiliate_network_id text,
    country text,
    offer_url text,
    primary_tag text,
    all_tags text,
    status text,
    is_active boolean DEFAULT true NOT NULL,
    deleted_at timestamp with time zone,
    batch_id integer,
    visits integer DEFAULT 0 NOT NULL,
    synced_at timestamp with time zone DEFAULT now()
);


--
-- Name: voluum_offers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.voluum_offers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: voluum_offers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.voluum_offers_id_seq OWNED BY public.voluum_offers.id;


--
-- Name: voluum_traffic_sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.voluum_traffic_sources (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    voluum_id text NOT NULL,
    name text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    deleted_at timestamp with time zone,
    synced_at timestamp with time zone DEFAULT now()
);


--
-- Name: voluum_traffic_sources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.voluum_traffic_sources_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: voluum_traffic_sources_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.voluum_traffic_sources_id_seq OWNED BY public.voluum_traffic_sources.id;


--
-- Name: worker_affiliate_networks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.worker_affiliate_networks (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    employee_id integer NOT NULL,
    affiliate_network_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: worker_affiliate_networks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.worker_affiliate_networks_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: worker_affiliate_networks_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.worker_affiliate_networks_id_seq OWNED BY public.worker_affiliate_networks.id;


--
-- Name: workspace_traffic_sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workspace_traffic_sources (
    id integer NOT NULL,
    workspace_id integer NOT NULL,
    name text NOT NULL,
    voluum_traffic_source_id text,
    "position" integer NOT NULL,
    is_active boolean DEFAULT true NOT NULL
);


--
-- Name: workspace_traffic_sources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.workspace_traffic_sources_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: workspace_traffic_sources_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.workspace_traffic_sources_id_seq OWNED BY public.workspace_traffic_sources.id;


--
-- Name: workspaces; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workspaces (
    id integer NOT NULL,
    name text NOT NULL,
    description text,
    is_active boolean DEFAULT false NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    voluum_access_id text,
    voluum_access_key text,
    voluum_api_base_url text,
    voluum_workspace_id text,
    voluum_workspace_name text,
    sync_interval text DEFAULT 'manual'::text NOT NULL,
    sync_status text,
    last_sync_at timestamp with time zone,
    traffic_sources_synced integer DEFAULT 0 NOT NULL,
    networks_synced integer DEFAULT 0 NOT NULL,
    overdue_threshold_hours integer DEFAULT 24 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: workspaces_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.workspaces_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: workspaces_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.workspaces_id_seq OWNED BY public.workspaces.id;


--
-- Name: affiliate_networks id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.affiliate_networks ALTER COLUMN id SET DEFAULT nextval('public.affiliate_networks_id_seq'::regclass);


--
-- Name: batch_results id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_results ALTER COLUMN id SET DEFAULT nextval('public.batch_results_id_seq'::regclass);


--
-- Name: batch_traffic_source_runs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_traffic_source_runs ALTER COLUMN id SET DEFAULT nextval('public.batch_traffic_source_runs_id_seq'::regclass);


--
-- Name: campaign_daily_metrics id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_daily_metrics ALTER COLUMN id SET DEFAULT nextval('public.campaign_daily_metrics_id_seq'::regclass);


--
-- Name: campaign_winners id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_winners ALTER COLUMN id SET DEFAULT nextval('public.campaign_winners_id_seq'::regclass);


--
-- Name: campaigns id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaigns ALTER COLUMN id SET DEFAULT nextval('public.campaigns_id_seq'::regclass);


--
-- Name: daily_reports id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_reports ALTER COLUMN id SET DEFAULT nextval('public.daily_reports_id_seq'::regclass);


--
-- Name: employee_workspace_assignments id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_workspace_assignments ALTER COLUMN id SET DEFAULT nextval('public.employee_workspace_assignments_id_seq'::regclass);


--
-- Name: employees id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees ALTER COLUMN id SET DEFAULT nextval('public.employees_id_seq'::regclass);


--
-- Name: events id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events ALTER COLUMN id SET DEFAULT nextval('public.events_id_seq'::regclass);


--
-- Name: geos id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.geos ALTER COLUMN id SET DEFAULT nextval('public.geos_id_seq'::regclass);


--
-- Name: goals id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals ALTER COLUMN id SET DEFAULT nextval('public.goals_id_seq'::regclass);


--
-- Name: imported_offers id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imported_offers ALTER COLUMN id SET DEFAULT nextval('public.imported_offers_id_seq'::regclass);


--
-- Name: notifications id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications ALTER COLUMN id SET DEFAULT nextval('public.notifications_id_seq'::regclass);


--
-- Name: offers id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.offers ALTER COLUMN id SET DEFAULT nextval('public.offers_id_seq'::regclass);


--
-- Name: operational_activity_feed id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operational_activity_feed ALTER COLUMN id SET DEFAULT nextval('public.operational_activity_feed_id_seq'::regclass);


--
-- Name: operational_events id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operational_events ALTER COLUMN id SET DEFAULT nextval('public.operational_events_id_seq'::regclass);


--
-- Name: performance id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.performance ALTER COLUMN id SET DEFAULT nextval('public.performance_id_seq'::regclass);


--
-- Name: settings id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings ALTER COLUMN id SET DEFAULT nextval('public.settings_id_seq'::regclass);


--
-- Name: testing_batches id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.testing_batches ALTER COLUMN id SET DEFAULT nextval('public.testing_batches_id_seq'::regclass);


--
-- Name: todo_tasks id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.todo_tasks ALTER COLUMN id SET DEFAULT nextval('public.todo_tasks_id_seq'::regclass);


--
-- Name: tracker_campaigns id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tracker_campaigns ALTER COLUMN id SET DEFAULT nextval('public.tracker_campaigns_id_seq'::regclass);


--
-- Name: voluum_affiliate_networks id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voluum_affiliate_networks ALTER COLUMN id SET DEFAULT nextval('public.voluum_affiliate_networks_id_seq'::regclass);


--
-- Name: voluum_campaign_mappings id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voluum_campaign_mappings ALTER COLUMN id SET DEFAULT nextval('public.voluum_campaign_mappings_id_seq'::regclass);


--
-- Name: voluum_campaigns id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voluum_campaigns ALTER COLUMN id SET DEFAULT nextval('public.voluum_campaigns_id_seq'::regclass);


--
-- Name: voluum_offers id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voluum_offers ALTER COLUMN id SET DEFAULT nextval('public.voluum_offers_id_seq'::regclass);


--
-- Name: voluum_traffic_sources id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voluum_traffic_sources ALTER COLUMN id SET DEFAULT nextval('public.voluum_traffic_sources_id_seq'::regclass);


--
-- Name: worker_affiliate_networks id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worker_affiliate_networks ALTER COLUMN id SET DEFAULT nextval('public.worker_affiliate_networks_id_seq'::regclass);


--
-- Name: workspace_traffic_sources id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_traffic_sources ALTER COLUMN id SET DEFAULT nextval('public.workspace_traffic_sources_id_seq'::regclass);


--
-- Name: workspaces id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspaces ALTER COLUMN id SET DEFAULT nextval('public.workspaces_id_seq'::regclass);


--
-- Name: affiliate_networks affiliate_networks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.affiliate_networks
    ADD CONSTRAINT affiliate_networks_pkey PRIMARY KEY (id);


--
-- Name: affiliate_networks affiliate_networks_workspace_name_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.affiliate_networks
    ADD CONSTRAINT affiliate_networks_workspace_name_unique UNIQUE (workspace_id, name);


--
-- Name: batch_results batch_results_batch_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_results
    ADD CONSTRAINT batch_results_batch_unique UNIQUE (batch_id);


--
-- Name: batch_results batch_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_results
    ADD CONSTRAINT batch_results_pkey PRIMARY KEY (id);


--
-- Name: batch_traffic_source_runs batch_traffic_source_runs_batch_position_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_traffic_source_runs
    ADD CONSTRAINT batch_traffic_source_runs_batch_position_unique UNIQUE (batch_id, "position");


--
-- Name: batch_traffic_source_runs batch_traffic_source_runs_batch_source_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_traffic_source_runs
    ADD CONSTRAINT batch_traffic_source_runs_batch_source_unique UNIQUE (batch_id, traffic_source_id);


--
-- Name: batch_traffic_source_runs batch_traffic_source_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_traffic_source_runs
    ADD CONSTRAINT batch_traffic_source_runs_pkey PRIMARY KEY (id);


--
-- Name: campaign_daily_metrics campaign_daily_metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_daily_metrics
    ADD CONSTRAINT campaign_daily_metrics_pkey PRIMARY KEY (id);


--
-- Name: campaign_daily_metrics campaign_daily_metrics_workspace_campaign_date_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_daily_metrics
    ADD CONSTRAINT campaign_daily_metrics_workspace_campaign_date_unique UNIQUE (campaign_id, date);


--
-- Name: campaign_winners campaign_winners_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_winners
    ADD CONSTRAINT campaign_winners_pkey PRIMARY KEY (id);


--
-- Name: campaign_winners campaign_winners_workspace_campaign_offer_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_winners
    ADD CONSTRAINT campaign_winners_workspace_campaign_offer_unique UNIQUE (workspace_id, campaign_id, offer_id);


--
-- Name: campaigns campaigns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaigns
    ADD CONSTRAINT campaigns_pkey PRIMARY KEY (id);


--
-- Name: daily_reports daily_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_reports
    ADD CONSTRAINT daily_reports_pkey PRIMARY KEY (id);


--
-- Name: employee_workspace_assignments employee_workspace_assignments_employee_id_workspace_id_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_workspace_assignments
    ADD CONSTRAINT employee_workspace_assignments_employee_id_workspace_id_unique UNIQUE (employee_id, workspace_id);


--
-- Name: employee_workspace_assignments employee_workspace_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_workspace_assignments
    ADD CONSTRAINT employee_workspace_assignments_pkey PRIMARY KEY (id);


--
-- Name: employees employees_email_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_email_unique UNIQUE (email);


--
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: geos geos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.geos
    ADD CONSTRAINT geos_pkey PRIMARY KEY (id);


--
-- Name: geos geos_workspace_code_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.geos
    ADD CONSTRAINT geos_workspace_code_unique UNIQUE (workspace_id, code);


--
-- Name: goals goals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_pkey PRIMARY KEY (id);


--
-- Name: imported_offers imported_offers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imported_offers
    ADD CONSTRAINT imported_offers_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: offers offers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_pkey PRIMARY KEY (id);


--
-- Name: operational_activity_feed operational_activity_feed_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operational_activity_feed
    ADD CONSTRAINT operational_activity_feed_pkey PRIMARY KEY (id);


--
-- Name: operational_events operational_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operational_events
    ADD CONSTRAINT operational_events_pkey PRIMARY KEY (id);


--
-- Name: performance performance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.performance
    ADD CONSTRAINT performance_pkey PRIMARY KEY (id);


--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (id);


--
-- Name: settings settings_workspace_key_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_workspace_key_unique UNIQUE (workspace_id, key);


--
-- Name: testing_batches testing_batches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.testing_batches
    ADD CONSTRAINT testing_batches_pkey PRIMARY KEY (id);


--
-- Name: testing_batches testing_batches_workspace_batch_tag_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.testing_batches
    ADD CONSTRAINT testing_batches_workspace_batch_tag_unique UNIQUE (workspace_id, batch_tag);


--
-- Name: todo_tasks todo_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.todo_tasks
    ADD CONSTRAINT todo_tasks_pkey PRIMARY KEY (id);


--
-- Name: tracker_campaigns tracker_campaigns_batch_source_device_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tracker_campaigns
    ADD CONSTRAINT tracker_campaigns_batch_source_device_unique UNIQUE (batch_id, traffic_source_id, device);


--
-- Name: tracker_campaigns tracker_campaigns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tracker_campaigns
    ADD CONSTRAINT tracker_campaigns_pkey PRIMARY KEY (id);


--
-- Name: tracker_campaigns tracker_campaigns_workspace_voluum_campaign_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tracker_campaigns
    ADD CONSTRAINT tracker_campaigns_workspace_voluum_campaign_unique UNIQUE (workspace_id, voluum_campaign_id);


--
-- Name: voluum_affiliate_networks voluum_affiliate_networks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voluum_affiliate_networks
    ADD CONSTRAINT voluum_affiliate_networks_pkey PRIMARY KEY (id);


--
-- Name: voluum_affiliate_networks voluum_affiliate_networks_workspace_voluum_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voluum_affiliate_networks
    ADD CONSTRAINT voluum_affiliate_networks_workspace_voluum_unique UNIQUE (workspace_id, voluum_id);


--
-- Name: voluum_campaign_mappings voluum_campaign_mappings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voluum_campaign_mappings
    ADD CONSTRAINT voluum_campaign_mappings_pkey PRIMARY KEY (id);


--
-- Name: voluum_campaign_mappings voluum_campaign_mappings_workspace_campaign_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voluum_campaign_mappings
    ADD CONSTRAINT voluum_campaign_mappings_workspace_campaign_unique UNIQUE (workspace_id, campaign_id);


--
-- Name: voluum_campaigns voluum_campaigns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voluum_campaigns
    ADD CONSTRAINT voluum_campaigns_pkey PRIMARY KEY (id);


--
-- Name: voluum_campaigns voluum_campaigns_workspace_campaign_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voluum_campaigns
    ADD CONSTRAINT voluum_campaigns_workspace_campaign_unique UNIQUE (workspace_id, campaign_id);


--
-- Name: voluum_offers voluum_offers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voluum_offers
    ADD CONSTRAINT voluum_offers_pkey PRIMARY KEY (id);


--
-- Name: voluum_offers voluum_offers_workspace_offer_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voluum_offers
    ADD CONSTRAINT voluum_offers_workspace_offer_unique UNIQUE (workspace_id, offer_id);


--
-- Name: voluum_traffic_sources voluum_traffic_sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voluum_traffic_sources
    ADD CONSTRAINT voluum_traffic_sources_pkey PRIMARY KEY (id);


--
-- Name: voluum_traffic_sources voluum_traffic_sources_workspace_voluum_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voluum_traffic_sources
    ADD CONSTRAINT voluum_traffic_sources_workspace_voluum_unique UNIQUE (workspace_id, voluum_id);


--
-- Name: worker_affiliate_networks worker_affiliate_networks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worker_affiliate_networks
    ADD CONSTRAINT worker_affiliate_networks_pkey PRIMARY KEY (id);


--
-- Name: worker_affiliate_networks worker_affiliate_networks_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worker_affiliate_networks
    ADD CONSTRAINT worker_affiliate_networks_unique UNIQUE (workspace_id, employee_id, affiliate_network_id);


--
-- Name: workspace_traffic_sources workspace_traffic_sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_traffic_sources
    ADD CONSTRAINT workspace_traffic_sources_pkey PRIMARY KEY (id);


--
-- Name: workspace_traffic_sources workspace_traffic_sources_workspace_name_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_traffic_sources
    ADD CONSTRAINT workspace_traffic_sources_workspace_name_unique UNIQUE (workspace_id, name);


--
-- Name: workspace_traffic_sources workspace_traffic_sources_workspace_position_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_traffic_sources
    ADD CONSTRAINT workspace_traffic_sources_workspace_position_unique UNIQUE (workspace_id, "position");


--
-- Name: workspaces workspaces_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspaces
    ADD CONSTRAINT workspaces_pkey PRIMARY KEY (id);


--
-- Name: events_workspace_pending_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX events_workspace_pending_idx ON public.events USING btree (workspace_id, processed_at, id);


--
-- Name: events_workspace_type_dedupe_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX events_workspace_type_dedupe_idx ON public.events USING btree (workspace_id, type, dedupe_key);


--
-- Name: operational_activity_feed_workspace_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX operational_activity_feed_workspace_created_at_idx ON public.operational_activity_feed USING btree (workspace_id, created_at);


--
-- Name: operational_activity_feed_workspace_event_type_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX operational_activity_feed_workspace_event_type_idx ON public.operational_activity_feed USING btree (workspace_id, event_type, created_at);


--
-- Name: operational_events_workspace_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX operational_events_workspace_created_at_idx ON public.operational_events USING btree (workspace_id, created_at, id);


--
-- Name: operational_events_workspace_entity_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX operational_events_workspace_entity_idx ON public.operational_events USING btree (workspace_id, entity_type, entity_id, created_at);


--
-- Name: operational_events_workspace_event_type_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX operational_events_workspace_event_type_idx ON public.operational_events USING btree (workspace_id, event_type, created_at);


--
-- Name: todo_tasks_open_batch_auto_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX todo_tasks_open_batch_auto_unique ON public.todo_tasks USING btree (workspace_id, related_batch_id, task_type) WHERE ((status = ANY (ARRAY['TODO'::public.task_status, 'IN_PROGRESS'::public.task_status])) AND (task_type = ANY (ARRAY['CREATE_IOS_CAMPAIGN'::public.task_type, 'CREATE_ANDROID_CAMPAIGN'::public.task_type, 'GO_LIVE'::public.task_type, 'OPTIMIZATION_FOLLOWUP'::public.task_type, 'MOVE_WINNERS_TO_SCALED_CAMPAIGN'::public.task_type])));


--
-- Name: todo_tasks_open_campaign_followup_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX todo_tasks_open_campaign_followup_unique ON public.todo_tasks USING btree (workspace_id, related_campaign_id, task_type) WHERE ((status = ANY (ARRAY['TODO'::public.task_status, 'IN_PROGRESS'::public.task_status])) AND (task_type = ANY (ARRAY['take_campaign_live'::public.task_type, 'find_winners'::public.task_type])) AND (related_campaign_id IS NOT NULL));


--
-- Name: todo_tasks_open_campaignops_terminal_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX todo_tasks_open_campaignops_terminal_unique ON public.todo_tasks USING btree (workspace_id, related_batch_id, task_type) WHERE ((status = ANY (ARRAY['TODO'::public.task_status, 'IN_PROGRESS'::public.task_status])) AND (task_type = 'all_traffic_sources_tested'::public.task_type));


--
-- Name: todo_tasks_open_create_campaign_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX todo_tasks_open_create_campaign_unique ON public.todo_tasks USING btree (workspace_id, related_batch_id, task_type) WHERE ((status = ANY (ARRAY['TODO'::public.task_status, 'IN_PROGRESS'::public.task_status])) AND (task_type = ANY (ARRAY['create_voluum_campaign_ios'::public.task_type, 'create_voluum_campaign_android'::public.task_type])));


--
-- Name: todo_tasks_open_tracker_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX todo_tasks_open_tracker_unique ON public.todo_tasks USING btree (workspace_id, related_batch_id, traffic_source_id, task_type, tracker_campaign_device) WHERE ((status = ANY (ARRAY['TODO'::public.task_status, 'IN_PROGRESS'::public.task_status])) AND (tracker_campaign_device IS NOT NULL));


--
-- Name: affiliate_networks affiliate_networks_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.affiliate_networks
    ADD CONSTRAINT affiliate_networks_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: batch_results batch_results_batch_id_testing_batches_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_results
    ADD CONSTRAINT batch_results_batch_id_testing_batches_id_fk FOREIGN KEY (batch_id) REFERENCES public.testing_batches(id) ON DELETE CASCADE;


--
-- Name: batch_results batch_results_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_results
    ADD CONSTRAINT batch_results_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: batch_traffic_source_runs batch_traffic_source_runs_android_campaign_id_campaigns_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_traffic_source_runs
    ADD CONSTRAINT batch_traffic_source_runs_android_campaign_id_campaigns_id_fk FOREIGN KEY (android_campaign_id) REFERENCES public.campaigns(id) ON DELETE SET NULL;


--
-- Name: batch_traffic_source_runs batch_traffic_source_runs_batch_id_testing_batches_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_traffic_source_runs
    ADD CONSTRAINT batch_traffic_source_runs_batch_id_testing_batches_id_fk FOREIGN KEY (batch_id) REFERENCES public.testing_batches(id) ON DELETE CASCADE;


--
-- Name: batch_traffic_source_runs batch_traffic_source_runs_ios_campaign_id_campaigns_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_traffic_source_runs
    ADD CONSTRAINT batch_traffic_source_runs_ios_campaign_id_campaigns_id_fk FOREIGN KEY (ios_campaign_id) REFERENCES public.campaigns(id) ON DELETE SET NULL;


--
-- Name: batch_traffic_source_runs batch_traffic_source_runs_traffic_source_id_workspace_traffic_s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_traffic_source_runs
    ADD CONSTRAINT batch_traffic_source_runs_traffic_source_id_workspace_traffic_s FOREIGN KEY (traffic_source_id) REFERENCES public.workspace_traffic_sources(id) ON DELETE RESTRICT;


--
-- Name: batch_traffic_source_runs batch_traffic_source_runs_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_traffic_source_runs
    ADD CONSTRAINT batch_traffic_source_runs_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: campaign_daily_metrics campaign_daily_metrics_campaign_id_campaigns_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_daily_metrics
    ADD CONSTRAINT campaign_daily_metrics_campaign_id_campaigns_id_fk FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;


--
-- Name: campaign_daily_metrics campaign_daily_metrics_employee_id_employees_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_daily_metrics
    ADD CONSTRAINT campaign_daily_metrics_employee_id_employees_id_fk FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE RESTRICT;


--
-- Name: campaign_daily_metrics campaign_daily_metrics_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_daily_metrics
    ADD CONSTRAINT campaign_daily_metrics_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: campaign_winners campaign_winners_batch_id_testing_batches_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_winners
    ADD CONSTRAINT campaign_winners_batch_id_testing_batches_id_fk FOREIGN KEY (batch_id) REFERENCES public.testing_batches(id) ON DELETE SET NULL;


--
-- Name: campaign_winners campaign_winners_campaign_id_campaigns_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_winners
    ADD CONSTRAINT campaign_winners_campaign_id_campaigns_id_fk FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;


--
-- Name: campaign_winners campaign_winners_detected_by_employee_id_employees_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_winners
    ADD CONSTRAINT campaign_winners_detected_by_employee_id_employees_id_fk FOREIGN KEY (detected_by_employee_id) REFERENCES public.employees(id) ON DELETE SET NULL;


--
-- Name: campaign_winners campaign_winners_traffic_source_id_workspace_traffic_sources_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_winners
    ADD CONSTRAINT campaign_winners_traffic_source_id_workspace_traffic_sources_id FOREIGN KEY (traffic_source_id) REFERENCES public.workspace_traffic_sources(id) ON DELETE SET NULL;


--
-- Name: campaign_winners campaign_winners_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaign_winners
    ADD CONSTRAINT campaign_winners_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: campaigns campaigns_affiliate_network_id_affiliate_networks_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaigns
    ADD CONSTRAINT campaigns_affiliate_network_id_affiliate_networks_id_fk FOREIGN KEY (affiliate_network_id) REFERENCES public.affiliate_networks(id) ON DELETE SET NULL;


--
-- Name: campaigns campaigns_batch_id_testing_batches_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaigns
    ADD CONSTRAINT campaigns_batch_id_testing_batches_id_fk FOREIGN KEY (batch_id) REFERENCES public.testing_batches(id) ON DELETE CASCADE;


--
-- Name: campaigns campaigns_geo_id_geos_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaigns
    ADD CONSTRAINT campaigns_geo_id_geos_id_fk FOREIGN KEY (geo_id) REFERENCES public.geos(id) ON DELETE SET NULL;


--
-- Name: campaigns campaigns_manual_closed_by_employee_id_employees_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaigns
    ADD CONSTRAINT campaigns_manual_closed_by_employee_id_employees_id_fk FOREIGN KEY (manual_closed_by_employee_id) REFERENCES public.employees(id) ON DELETE SET NULL;


--
-- Name: campaigns campaigns_traffic_source_id_workspace_traffic_sources_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaigns
    ADD CONSTRAINT campaigns_traffic_source_id_workspace_traffic_sources_id_fk FOREIGN KEY (traffic_source_id) REFERENCES public.workspace_traffic_sources(id) ON DELETE SET NULL;


--
-- Name: campaigns campaigns_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.campaigns
    ADD CONSTRAINT campaigns_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: daily_reports daily_reports_employee_id_employees_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_reports
    ADD CONSTRAINT daily_reports_employee_id_employees_id_fk FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;


--
-- Name: daily_reports daily_reports_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_reports
    ADD CONSTRAINT daily_reports_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: employees employees_active_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_active_workspace_id_workspaces_id_fk FOREIGN KEY (active_workspace_id) REFERENCES public.workspaces(id) ON DELETE SET NULL;


--
-- Name: events events_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: geos geos_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.geos
    ADD CONSTRAINT geos_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: goals goals_employee_id_employees_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_employee_id_employees_id_fk FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;


--
-- Name: goals goals_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: imported_offers imported_offers_batch_id_testing_batches_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imported_offers
    ADD CONSTRAINT imported_offers_batch_id_testing_batches_id_fk FOREIGN KEY (batch_id) REFERENCES public.testing_batches(id) ON DELETE SET NULL;


--
-- Name: imported_offers imported_offers_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.imported_offers
    ADD CONSTRAINT imported_offers_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: notifications notifications_batch_id_testing_batches_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_batch_id_testing_batches_id_fk FOREIGN KEY (batch_id) REFERENCES public.testing_batches(id) ON DELETE SET NULL;


--
-- Name: notifications notifications_employee_id_employees_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_employee_id_employees_id_fk FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;


--
-- Name: notifications notifications_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: offers offers_batch_id_testing_batches_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_batch_id_testing_batches_id_fk FOREIGN KEY (batch_id) REFERENCES public.testing_batches(id) ON DELETE CASCADE;


--
-- Name: offers offers_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: operational_activity_feed operational_activity_feed_actor_employee_id_employees_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operational_activity_feed
    ADD CONSTRAINT operational_activity_feed_actor_employee_id_employees_id_fk FOREIGN KEY (actor_employee_id) REFERENCES public.employees(id) ON DELETE SET NULL;


--
-- Name: operational_activity_feed operational_activity_feed_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operational_activity_feed
    ADD CONSTRAINT operational_activity_feed_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: operational_events operational_events_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operational_events
    ADD CONSTRAINT operational_events_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: performance performance_batch_id_testing_batches_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.performance
    ADD CONSTRAINT performance_batch_id_testing_batches_id_fk FOREIGN KEY (batch_id) REFERENCES public.testing_batches(id) ON DELETE CASCADE;


--
-- Name: settings settings_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: testing_batches testing_batches_affiliate_network_id_affiliate_networks_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.testing_batches
    ADD CONSTRAINT testing_batches_affiliate_network_id_affiliate_networks_id_fk FOREIGN KEY (affiliate_network_id) REFERENCES public.affiliate_networks(id) ON DELETE RESTRICT;


--
-- Name: testing_batches testing_batches_current_traffic_source_id_voluum_traffic_source; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.testing_batches
    ADD CONSTRAINT testing_batches_current_traffic_source_id_voluum_traffic_source FOREIGN KEY (current_traffic_source_id) REFERENCES public.voluum_traffic_sources(id) ON DELETE SET NULL;


--
-- Name: testing_batches testing_batches_current_workspace_traffic_source_id_workspace_t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.testing_batches
    ADD CONSTRAINT testing_batches_current_workspace_traffic_source_id_workspace_t FOREIGN KEY (current_workspace_traffic_source_id) REFERENCES public.workspace_traffic_sources(id) ON DELETE SET NULL;


--
-- Name: testing_batches testing_batches_employee_id_employees_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.testing_batches
    ADD CONSTRAINT testing_batches_employee_id_employees_id_fk FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;


--
-- Name: testing_batches testing_batches_geo_id_geos_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.testing_batches
    ADD CONSTRAINT testing_batches_geo_id_geos_id_fk FOREIGN KEY (geo_id) REFERENCES public.geos(id) ON DELETE RESTRICT;


--
-- Name: testing_batches testing_batches_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.testing_batches
    ADD CONSTRAINT testing_batches_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: todo_tasks todo_tasks_completed_by_employee_id_employees_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.todo_tasks
    ADD CONSTRAINT todo_tasks_completed_by_employee_id_employees_id_fk FOREIGN KEY (completed_by_employee_id) REFERENCES public.employees(id) ON DELETE SET NULL;


--
-- Name: todo_tasks todo_tasks_employee_id_employees_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.todo_tasks
    ADD CONSTRAINT todo_tasks_employee_id_employees_id_fk FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;


--
-- Name: todo_tasks todo_tasks_related_batch_id_testing_batches_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.todo_tasks
    ADD CONSTRAINT todo_tasks_related_batch_id_testing_batches_id_fk FOREIGN KEY (related_batch_id) REFERENCES public.testing_batches(id) ON DELETE SET NULL;


--
-- Name: todo_tasks todo_tasks_traffic_source_id_workspace_traffic_sources_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.todo_tasks
    ADD CONSTRAINT todo_tasks_traffic_source_id_workspace_traffic_sources_id_fk FOREIGN KEY (traffic_source_id) REFERENCES public.workspace_traffic_sources(id) ON DELETE SET NULL;


--
-- Name: todo_tasks todo_tasks_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.todo_tasks
    ADD CONSTRAINT todo_tasks_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: tracker_campaigns tracker_campaigns_batch_id_testing_batches_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tracker_campaigns
    ADD CONSTRAINT tracker_campaigns_batch_id_testing_batches_id_fk FOREIGN KEY (batch_id) REFERENCES public.testing_batches(id) ON DELETE CASCADE;


--
-- Name: tracker_campaigns tracker_campaigns_traffic_source_id_voluum_traffic_sources_id_f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tracker_campaigns
    ADD CONSTRAINT tracker_campaigns_traffic_source_id_voluum_traffic_sources_id_f FOREIGN KEY (traffic_source_id) REFERENCES public.voluum_traffic_sources(id) ON DELETE RESTRICT;


--
-- Name: tracker_campaigns tracker_campaigns_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tracker_campaigns
    ADD CONSTRAINT tracker_campaigns_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: voluum_campaign_mappings voluum_campaign_mappings_batch_id_testing_batches_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voluum_campaign_mappings
    ADD CONSTRAINT voluum_campaign_mappings_batch_id_testing_batches_id_fk FOREIGN KEY (batch_id) REFERENCES public.testing_batches(id) ON DELETE CASCADE;


--
-- Name: voluum_campaign_mappings voluum_campaign_mappings_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voluum_campaign_mappings
    ADD CONSTRAINT voluum_campaign_mappings_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: worker_affiliate_networks worker_affiliate_networks_affiliate_network_id_affiliate_networ; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worker_affiliate_networks
    ADD CONSTRAINT worker_affiliate_networks_affiliate_network_id_affiliate_networ FOREIGN KEY (affiliate_network_id) REFERENCES public.affiliate_networks(id) ON DELETE CASCADE;


--
-- Name: worker_affiliate_networks worker_affiliate_networks_employee_id_employees_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worker_affiliate_networks
    ADD CONSTRAINT worker_affiliate_networks_employee_id_employees_id_fk FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;


--
-- Name: worker_affiliate_networks worker_affiliate_networks_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worker_affiliate_networks
    ADD CONSTRAINT worker_affiliate_networks_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: workspace_traffic_sources workspace_traffic_sources_workspace_id_workspaces_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_traffic_sources
    ADD CONSTRAINT workspace_traffic_sources_workspace_id_workspaces_id_fk FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


